# Generated by Django 6.0.2 on 2026-02-22 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('LATE', 'Late')], default='PENDING', max_length=10)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('tenancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.tenancy')),
            ],
            options={
                'unique_together': {('tenancy', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('ONLINE', 'Online'), ('BANK', 'Bank'), ('ESEWA', 'eSewa')], max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=50, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.rentinvoice')),
            ],
        ),
    ]
