# Generated by Django 6.0.2 on 2026-03-01 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_rentinvoice_vat_amount_expense'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentinvoice',
            name='vat_amount',
        ),
    ]
