# Generated by Django on add awaiting status to invoices

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_remove_rentinvoice_vat_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentinvoice',
            name='status',
            field=models.CharField(
                choices=[
                    ('PENDING', 'Pending'),
                    ('AWAITING', 'Awaiting Confirmation'),
                    ('PAID', 'Paid'),
                    ('LATE', 'Late'),
                ],
                default='PENDING',
                max_length=10,
                db_index=True,
            ),
        ),
    ]
