# Generated by Django 6.0.2 on 2026-02-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenancy',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
