# Generated by Django 6.0.2 on 2026-02-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('LANDLORD', 'Landlord'), ('TENANT', 'Tenant')], db_index=True, default='TENANT', max_length=10),
        ),
    ]
