# Generated by Django 6.0.2 on 2026-02-28 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='needs_password_change',
            field=models.BooleanField(default=False),
        ),
    ]
