# Generated by Django 6.0.2 on 2026-02-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentinvoice',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('LATE', 'Late')], db_index=True, default='PENDING', max_length=10),
        ),
    ]
